enum MACHINE_RUNS
{
	RUN_ONLOAD,
	RUN_PNP_ARM,
    RUN_UNLOAD,
    NUM_OF_RUNS,
};

enum MACHINE_MOTORS
{
	MOTOR_ARM_X_AXIS,
    MOTOR_ARM_Z_AXIS,
    NUM_OF_MOTORS,
};

enum MACHINE_INPUTS
{
    I_START,							// X0000
    I_STOP,								// X0001
    I_RESET,							// X0002
	I_E_STOP,
	I_ONLOAD_STRIP_PRESENT,
	I_INPUT_RESERVE_5,
	I_INPUT_RESERVE_6,
	I_VACUUM_ON,
	I_ONLOAD_UP_LIMIT,
	I_ONLOAD_DOWN_LIMIT,
	I_UNLOAD_UP_LIMIT,
	I_UNLOAD_DOWN_LIMIT,
	I_UNLOAD_STRIP_PRESENT,
	I_ONLOAD_MAG_LOCK,
	I_UNLOAD_MAG_LOCK,
    NUM_OF_INPUTS
};

enum MACHINE_OUTPUTS
{
	O_START_BTN_LED,					// Y0000
	O_STOP_BTN_LED,						// Y0001
	O_RESET_BTN_LED,					// Y0002
	O_RED_TOWER_LIGHT,					// Y0003
	O_AMBER_TOWER_LIGHT,				// Y0004
	O_GREEN_TOWER_LIGHT,				// Y0005
    O_BUZZER,	
	O_VACUUM_VALVE,
	O_ONLOAD_MOVE_UP,
	O_ONLOAD_MOVE_DOWN,
	O_ONLOAD_BREAKER,
	O_UNLOAD_MOVE_UP,
	O_UNLOAD_MOVE_DOWN,
	O_UNLOAD_BREAKER,
	O_ONLOAD_MAG_LOCK_CLY,
	O_UNLOAD_MAG_LOCK_CLY,
	NUM_OF_OUTPUTS
};

enum MACHINE_EVENTS
{
	EVT_ONLOAD_READY,
	EVT_PICK_END,
	EVT_PLACE_END,
    EVT_UNLOAD_READY,
	NUM_OF_EVENTS
};

enum MOTOR_LOCATIONS
{
	// onload stacter
	// Pnp Arm x axis
	LOC_ARM_AT_ONLOAD = 0,
	LOC_ARM_AT_UNLOAD,
	// Pnp Arm Z axis
	LOC_ARM_AT_UP = 0,
	LOC_ARM_AT_DOWN,
};

enum MACHINE_TIMES
{
  TIME_ONLOAD_UP,
  TIME_UNLOAD_UP,
  NUM_OF_MACHINE_TIME
};

enum MSG_ID
{
  MSG_ONLOAD_MOVE_UP_TIMEOUT			= 1001,
  MSG_ONLOAD_MOVE_DOWN_TIMEOUT			= 1002,
  MSG_UNLOAD_MOVE_UP_TIMEOUT			= 1003,
  MSG_UNLOAD_MOVE_DOWN_TIMEOUT			= 1004,
};