// ATLProject.idl: ATLProject 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 生成类型库(ATLProject.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(0656ea0a-b2c0-40f5-8859-bdadd11ed590),
	version(1.0),
]
library ATLProjectLib
{
	importlib("stdole2.tlb");
};

